name: recyclear
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  flutter_bloc: ^8.1.3 
  cloud_firestore: ^4.15.10
  image_picker: ^0.8.1
  firebase_storage: ^11.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  reviews_slider: ^2.0.0
  

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true