// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDeuy4-w3DTBzQoBjr9k8BlMosRbksMGg',
    appId: '1:801296718867:web:7966b8ee715aca5d7333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    authDomain: 'graduation-project-47c85.firebaseapp.com',
    databaseURL: 'https://graduation-project-47c85-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-47c85.appspot.com',
    measurementId: 'G-Q0ZPPVZM2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBahmAe9lq9SnI4kZIJh1ZUTwbkiI1Ea-w',
    appId: '1:801296718867:android:40e3af5517dd74897333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    databaseURL: 'https://graduation-project-47c85-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-47c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpyYFRCCavlDxza23JnmB2Cm1B5-G1Dbs',
    appId: '1:801296718867:ios:8c07e289a236f1fb7333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    databaseURL: 'https://graduation-project-47c85-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-47c85.appspot.com',
    iosBundleId: 'com.example.recyclear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpyYFRCCavlDxza23JnmB2Cm1B5-G1Dbs',
    appId: '1:801296718867:ios:cb7d346e831160eb7333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    databaseURL: 'https://graduation-project-47c85-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-47c85.appspot.com',
    iosBundleId: 'com.example.recyclear.RunnerTests',
  );
}
