// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvEt73IoQo-UYgbMpzkoJvFnlF8allinc',
    appId: '1:801296718867:web:7966b8ee715aca5d7333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    authDomain: 'graduation-project-47c85.firebaseapp.com',
    storageBucket: 'graduation-project-47c85.appspot.com',
    measurementId: 'G-Q0ZPPVZM2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgpThI8o5GdwohohRleVsZC38T37kBWo',
    appId: '1:801296718867:android:8b91ad6155b1328d7333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    storageBucket: 'graduation-project-47c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAciMVouN2OmS1BnaDSvfU7n_f-9oe9ppU',
    appId: '1:801296718867:ios:668d35a07d2023a77333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    storageBucket: 'graduation-project-47c85.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAciMVouN2OmS1BnaDSvfU7n_f-9oe9ppU',
    appId: '1:801296718867:ios:91d742ab17bfa7f27333e6',
    messagingSenderId: '801296718867',
    projectId: 'graduation-project-47c85',
    storageBucket: 'graduation-project-47c85.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
